/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlytiemnail;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author trand
 */
public class SuaThongTinNhanVien extends javax.swing.JFrame {
    Connection conn = connectdata.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    String tennd1;
    String id1;
    /**
     * Creates new form SuaThongTinNhanVien
     */
    public SuaThongTinNhanVien() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jr_nu);
        bg.add(jr_nam);
        jr_nam.setSelected(true);
        setLocationRelativeTo(null);
    }
    public SuaThongTinNhanVien(String tennd, String id) {
        initComponents();
        tennd1 = tennd;
        id1 = id;
        ButtonGroup bg = new ButtonGroup();
        bg.add(jr_nu);
        bg.add(jr_nam);
        jr_nam.setSelected(true);
        setLocationRelativeTo(null);
        jid.setText(id);
    }
    public SuaThongTinNhanVien(String tennd, String id, String tennv, String sdtnv, String gt, String ns, String luong) {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jr_nu);
        bg.add(jr_nam);
        jid.setText(id);
        jtennv.setText(tennv);
        jsdt.setText(sdtnv);
        if("Nam".equals(gt)){
            jr_nam.setSelected(true);
        }else{
            jr_nu.setSelected(true);
        }
        String ngay= "", thang = "", nam = "";
        char x[] = ns.toCharArray();
        int y = 0;
        while(x[y] != '-'){
            nam += x[y];
            y++;
        }
        y++;
        while(x[y] != '-'){
            thang += x[y];
            y++;
        }
        y++;
        while(y < x.length){
            ngay += x[y];
            y++;
        }
        jngay.setText(ngay);
        jthang.setText(thang);
        jnam.setText(nam);
        jluong.setText(luong);
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jtennv = new javax.swing.JTextField();
        jsdt = new javax.swing.JTextField();
        jngay = new javax.swing.JTextField();
        jluong = new javax.swing.JTextField();
        jb_thaydoi = new javax.swing.JButton();
        jb_back = new javax.swing.JButton();
        jr_nam = new javax.swing.JRadioButton();
        jr_nu = new javax.swing.JRadioButton();
        jthang = new javax.swing.JTextField();
        jnam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sửa thông tin nhân viên");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 40, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("SỬA THÔNG TIN NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID NHÂN VIÊN: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên Nhân viên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giới tính:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Lương:");

        jid.setFocusable(false);

        jsdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsdtKeyPressed(evt);
            }
        });

        jngay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jngayKeyPressed(evt);
            }
        });

        jluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jluongKeyPressed(evt);
            }
        });

        jb_thaydoi.setBackground(new java.awt.Color(40, 167, 69));
        jb_thaydoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_thaydoi.setForeground(new java.awt.Color(255, 255, 255));
        jb_thaydoi.setText("THAY ĐỔI");
        jb_thaydoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_thaydoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_thaydoiActionPerformed(evt);
            }
        });

        jb_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_back.setForeground(new java.awt.Color(0, 123, 255));
        jb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jb_back.setText("TRỞ VỀ");
        jb_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_backActionPerformed(evt);
            }
        });

        jr_nam.setText("Nam");
        jr_nam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jr_nu.setText("Nữ");
        jr_nu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jthang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jthangKeyPressed(evt);
            }
        });

        jnam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jnamKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_thaydoi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jid)
                            .addComponent(jtennv)
                            .addComponent(jsdt)
                            .addComponent(jluong)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jr_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(jr_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jngay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jthang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jnam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jr_nam)
                    .addComponent(jr_nu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_thaydoi)
                    .addComponent(jb_back))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean check(int day, int month, int year) {
        boolean isValid = true;
        try {
            LocalDate.of(year, month, day);
        } catch (Exception e) {
            isValid = false;
        }

        return isValid;
    }
    private void jb_thaydoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_thaydoiActionPerformed
        // TODO add your handling code here:
        LocalDate x = LocalDate.now();
        if (jtennv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên nhân viên !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtennv.requestFocus();
        } else if(jsdt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống số điện thoại !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jsdt.requestFocus();
        }else if(jngay.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống ngày sinh !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jngay.requestFocus();
        }else if(jthang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống tháng sinh !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jthang.requestFocus();
        }else if(jnam.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống năm sinh !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jnam.requestFocus();
        }else if(jluong.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống lương !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jluong.requestFocus();
        }else if (jsdt.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Độ dài số điện thoại không hợp lệ !", "thông báo", JOptionPane.WARNING_MESSAGE);
        }
        else if (check(Integer.parseInt(jngay.getText()), Integer.parseInt(jthang.getText()), Integer.parseInt(jnam.getText())) == false) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ !", "thông báo", JOptionPane.WARNING_MESSAGE);
        }else if(Integer.parseInt(jnam.getText()) > x.getYear()){
            JOptionPane.showMessageDialog(this, "Mới có năm 2023 đâu ra bà sinh năm lớn hơn được -.- !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jnam.requestFocus();
        }else if(Integer.parseInt(jnam.getText()) == x.getYear() && Integer.parseInt(jthang.getText()) > x.getMonthValue()){
            JOptionPane.showMessageDialog(this, "Mới có tháng 06 sao mà bà sinh lớn hơn được -.- !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jthang.requestFocus();
        }else if(Integer.parseInt(jnam.getText()) == x.getYear() && Integer.parseInt(jthang.getText()) == x.getMonthValue() && Integer.parseInt(jngay.getText()) > x.getDayOfMonth()){
            JOptionPane.showMessageDialog(this, "Không thể nhập ngày lớn hơn ngày hiện tại !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jngay.requestFocus();
        }
        else{
            String gioitinh = "Nam";
            if(jr_nu.isSelected()){
                gioitinh = "Nữ";
            }
            String ngaysinh = jnam.getText() + "-" + jthang.getText() + "-" + jngay.getText();
            try{
                String query = """
                call updateTableNhanVien(?, ?, ?, ?, ?, ?);
                """;
                pst = conn.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(id1));
                pst.setString(2, jtennv.getText());
                pst.setString(3, jsdt.getText());
                pst.setString(5, ngaysinh);
                pst.setString(4, gioitinh);
                pst.setInt(6, Integer.parseInt(jluong.getText()));
                pst.executeQuery();
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công !");
                jtennv.setText("");
                jsdt.setText("");
                jngay.setText("");
                jthang.setText("");
                jnam.setText("");
                jr_nam.setSelected(true);
                jluong.setText("");
                jtennv.requestFocus();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_jb_thaydoiActionPerformed

    private void jb_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_backActionPerformed
        // TODO add your handling code here:
        new QLTN(tennd1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jb_backActionPerformed

    private void jluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jluongKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Lương phải là một số nguyên dương !");
            jluong.setText("");
            jluong.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jluong.setText("");
            jluong.requestFocus();
        }
    }//GEN-LAST:event_jluongKeyPressed

    private void jsdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsdtKeyPressed
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar())){
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jsdt.setText("");
            jsdt.requestFocus();
        }
    }//GEN-LAST:event_jsdtKeyPressed

    private void jngayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jngayKeyPressed
        // TODO add your handling code here:
       if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Lương phải là một số nguyên dương !");
            jngay.setText("");
            jngay.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jngay.setText("");
            jngay.requestFocus();
        }
    }//GEN-LAST:event_jngayKeyPressed

    private void jthangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jthangKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Lương phải là một số nguyên dương !");
            jthang.setText("");
            jthang.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jthang.setText("");
            jthang.requestFocus();
        }
    }//GEN-LAST:event_jthangKeyPressed

    private void jnamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnamKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Lương phải là một số nguyên dương !");
            jnam.setText("");
            jnam.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jnam.setText("");
            jnam.requestFocus();
        }
    }//GEN-LAST:event_jnamKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaThongTinNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb_back;
    private javax.swing.JButton jb_thaydoi;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jluong;
    private javax.swing.JTextField jnam;
    private javax.swing.JTextField jngay;
    private javax.swing.JRadioButton jr_nam;
    private javax.swing.JRadioButton jr_nu;
    private javax.swing.JTextField jsdt;
    private javax.swing.JTextField jtennv;
    private javax.swing.JTextField jthang;
    // End of variables declaration//GEN-END:variables
}
