/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlytiemnail;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author trand
 */
public class SuaThongTinKhachHang extends javax.swing.JFrame {
    Connection conn = connectdata.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    String tennd1;
    String id1;
    /**
     * Creates new form SuaThongTinKhachHang
     */
    public SuaThongTinKhachHang() {
        initComponents();
        setLocationRelativeTo(null);
        ButtonGroup bg = new ButtonGroup();
        bg.add(jr_nu);
        bg.add(jr_nam);
        jr_nam.setSelected(true);
    }
    public SuaThongTinKhachHang(String tennd, String id) {
        initComponents();
        tennd1 = tennd;
        id1 = id;
        jid.setText(id1);
        setLocationRelativeTo(null);
        ButtonGroup bg = new ButtonGroup();
        bg.add(jr_nu);
        bg.add(jr_nam);
        jr_nam.setSelected(true);
    }
    public SuaThongTinKhachHang(String tennd, String id, String tenkh, String sdtkh, String email, String gt, String dc) {
        initComponents();
        tennd1 = tennd;
        id1 = id;
        jid.setText(id1);
        jtenkh.setText(tenkh);
        jsdt.setText(sdtkh);
        jemail.setText(email);
        if("Nam".equals(gt)){
            jr_nam.setSelected(true);
        }else{
            jr_nu.setSelected(true);
        }
        jdiachi.setText(dc);
        setLocationRelativeTo(null);
        ButtonGroup bg = new ButtonGroup();
        bg.add(jr_nu);
        bg.add(jr_nam);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jtenkh = new javax.swing.JTextField();
        jsdt = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jdiachi = new javax.swing.JTextField();
        jb_thaydoi = new javax.swing.JButton();
        jb_back = new javax.swing.JButton();
        jr_nam = new javax.swing.JRadioButton();
        jr_nu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sửa thông tin khách hàng");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 40, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("SỬA THÔNG TIN KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID KHÁCH HÀNG: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên khách hàng: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giới tính:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jid.setFocusable(false);

        jsdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsdtKeyPressed(evt);
            }
        });

        jb_thaydoi.setBackground(new java.awt.Color(40, 167, 69));
        jb_thaydoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_thaydoi.setForeground(new java.awt.Color(255, 255, 255));
        jb_thaydoi.setText("THAY ĐỔI");
        jb_thaydoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_thaydoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_thaydoiActionPerformed(evt);
            }
        });

        jb_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_back.setForeground(new java.awt.Color(0, 123, 255));
        jb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jb_back.setText("TRỞ VỀ");
        jb_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_backActionPerformed(evt);
            }
        });

        jr_nam.setText("Nam");
        jr_nam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jr_nu.setText("Nữ");
        jr_nu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_thaydoi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jid)
                            .addComponent(jtenkh)
                            .addComponent(jsdt)
                            .addComponent(jemail)
                            .addComponent(jdiachi)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jr_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(jr_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jr_nam)
                    .addComponent(jr_nu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_thaydoi)
                    .addComponent(jb_back))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jb_thaydoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_thaydoiActionPerformed
        // TODO add your handling code here:
        
        if(jtenkh.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống tên khách hàng !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            jtenkh.requestFocus();
        }else if(jsdt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống số điện thoại !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            jsdt.requestFocus();
        }else if(jemail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống email !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            jemail.requestFocus();
        }else if(jdiachi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống địa chỉ !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            jdiachi.requestFocus();
        }else if (jsdt.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Độ dài số điện thoại không hợp lệ !", "thông báo", JOptionPane.WARNING_MESSAGE);
        }else{
            String gioitinh = "Nam";
            if(jr_nu.isSelected()){
                gioitinh = "Nữ";
            }
            try{
                String query = """
                               call updateTableKhachHang(?, ?, ?, ?, ?, ?);
                               """;
                pst = conn.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(id1));
                pst.setString(2, jtenkh.getText());
                pst.setString(3, jsdt.getText());
                pst.setString(4, jemail.getText());
                pst.setString(5, gioitinh);
                pst.setString(6, jdiachi.getText());
                pst.executeQuery();
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công !");
                jtenkh.setText("");
                jsdt.setText("");
                jemail.setText("");
                jr_nam.setSelected(true);
                jdiachi.setText("");
                jtenkh.requestFocus();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_jb_thaydoiActionPerformed

    private void jb_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_backActionPerformed
        // TODO add your handling code here:
        new QLTN(tennd1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jb_backActionPerformed

    private void jsdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsdtKeyPressed
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar())){
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự");
            jsdt.setText("");
            jsdt.requestFocus();
        }
    }//GEN-LAST:event_jsdtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaThongTinKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb_back;
    private javax.swing.JButton jb_thaydoi;
    private javax.swing.JTextField jdiachi;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jid;
    private javax.swing.JRadioButton jr_nam;
    private javax.swing.JRadioButton jr_nu;
    private javax.swing.JTextField jsdt;
    private javax.swing.JTextField jtenkh;
    // End of variables declaration//GEN-END:variables
}
