/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlytiemnail;

import java.time.LocalDate;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author trand
 */
public class ThemThongTinNhanVien extends javax.swing.JFrame {

    Connection conn = connectdata.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    String tennd;
    int idtk_cur;

    /**
     * Creates new form ThemThongTinNhanVien
     */
    public ThemThongTinNhanVien() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jrb_nam);
        bg.add(jrb_nu);
        jrb_nam.setSelected(true);
        jtext_nhanvien.requestFocus();
        setLocationRelativeTo(null);
        try{
            String query = """
                           select count(idtk) from taikhoan
                           """;
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                idtk_cur = rs.getInt(1);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public ThemThongTinNhanVien(String tennguoidung) {
        initComponents();
        setLocationRelativeTo(null);
        ButtonGroup bg = new ButtonGroup();
        bg.add(jrb_nam);
        bg.add(jrb_nu);
        jrb_nam.setSelected(true);
        jtext_nhanvien.requestFocus();
        tennd = tennguoidung;
        try{
            String query = """
                           select count(idtk) from taikhoan
                           """;
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                idtk_cur = rs.getInt(1);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jb_back = new javax.swing.JButton();
        jtext_nhanvien = new javax.swing.JTextField();
        jtext_sdt = new javax.swing.JTextField();
        jtext_luong = new javax.swing.JTextField();
        jb_thuchien = new javax.swing.JButton();
        jrb_nam = new javax.swing.JRadioButton();
        jrb_nu = new javax.swing.JRadioButton();
        jtext_ngay = new javax.swing.JTextField();
        jtext_thang = new javax.swing.JTextField();
        jtext_nam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm thông tin nhân viên");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 40, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("THÊM THÔNG TIN NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên nhân viên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày sinh:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Lương:");

        jb_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_back.setForeground(new java.awt.Color(0, 123, 255));
        jb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jb_back.setText("TRỞ VỀ");
        jb_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_backActionPerformed(evt);
            }
        });

        jtext_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_sdtActionPerformed(evt);
            }
        });
        jtext_sdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext_sdtKeyPressed(evt);
            }
        });

        jtext_luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_luongActionPerformed(evt);
            }
        });
        jtext_luong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext_luongKeyPressed(evt);
            }
        });

        jb_thuchien.setBackground(new java.awt.Color(40, 167, 69));
        jb_thuchien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_thuchien.setForeground(new java.awt.Color(255, 255, 255));
        jb_thuchien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-button.png"))); // NOI18N
        jb_thuchien.setText("Thêm");
        jb_thuchien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_thuchien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_thuchienActionPerformed(evt);
            }
        });

        jrb_nam.setText("Nam");
        jrb_nam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jrb_nu.setText("Nữ");
        jrb_nu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrb_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_nuActionPerformed(evt);
            }
        });

        jtext_ngay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext_ngayKeyPressed(evt);
            }
        });

        jtext_thang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext_thangKeyPressed(evt);
            }
        });

        jtext_nam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtext_namKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtext_luong, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtext_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtext_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtext_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtext_nhanvien)
                                    .addComponent(jtext_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jb_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_thuchien)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtext_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtext_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtext_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtext_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtext_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrb_nam)
                    .addComponent(jrb_nu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtext_luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_back)
                    .addComponent(jb_thuchien))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtext_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_sdtActionPerformed

    private void jrb_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_nuActionPerformed

    private void jb_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_backActionPerformed
        // TODO add your handling code here:
        new QLTN(tennd).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jb_backActionPerformed

    private void jtext_luongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_luongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_luongActionPerformed

    private void jtext_luongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext_luongKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Lương phải là một số nguyên dương !");
            jtext_luong.setText("");
            jtext_luong.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jtext_luong.setText("");
            jtext_luong.requestFocus();
        }
    }//GEN-LAST:event_jtext_luongKeyPressed
    public boolean check(int day, int month, int year) {
        boolean isValid = true;
        try {
            LocalDate.of(year, month, day);
        } catch (Exception e) {
            isValid = false;
        }

        return isValid;
    }
    private void jb_thuchienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_thuchienActionPerformed
        // TODO add your handling code here:
        LocalDate x = LocalDate.now();
        if (jtext_nhanvien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên nhân viên !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_nhanvien.requestFocus();
        } else if(jtext_sdt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống số điện thoại !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_sdt.requestFocus();
        }else if(jtext_ngay.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống ngày sinh !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_ngay.requestFocus();
        }else if(jtext_thang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống tháng sinh !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_thang.requestFocus();
        }else if(jtext_nam.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống năm sinh !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_nam.requestFocus();
        }else if(jtext_luong.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống lương !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_luong.requestFocus();
        }
        else if (jtext_sdt.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Độ dài số điện thoại không hợp lệ !", "thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (check(Integer.parseInt(jtext_ngay.getText()), Integer.parseInt(jtext_thang.getText()), Integer.parseInt(jtext_nam.getText())) == false) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ !", "thông báo", JOptionPane.WARNING_MESSAGE);
        } else if(Integer.parseInt(jtext_nam.getText()) > x.getYear()){
            JOptionPane.showMessageDialog(this, "Mới có năm 2023 đâu ra bà sinh năm lớn hơn được -.- !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_nam.requestFocus();
        }else if(Integer.parseInt(jtext_nam.getText()) == x.getYear() && Integer.parseInt(jtext_thang.getText()) > x.getMonthValue()){
            JOptionPane.showMessageDialog(this, "Mới có tháng 06 sao mà bà sinh lớn hơn được -.- !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_thang.requestFocus();
        }else if(Integer.parseInt(jtext_nam.getText()) == x.getYear() && Integer.parseInt(jtext_thang.getText()) == x.getMonthValue() && Integer.parseInt(jtext_ngay.getText()) > x.getDayOfMonth()){
            JOptionPane.showMessageDialog(this, "Không thể nhập ngày lớn hơn ngày hiện tại !", "thông báo", JOptionPane.WARNING_MESSAGE);
            jtext_ngay.requestFocus();
        }else {
            try {
                String tennv = jtext_nhanvien.getText();
                String sdt = jtext_sdt.getText();
                String gioitinh = "";
                if (jrb_nam.isSelected()) {
                    gioitinh += "Nam";
                } else {
                    gioitinh += "Nữ";
                }
                String ngaysinh = jtext_nam.getText() + "-" + jtext_thang.getText() + "-" + jtext_ngay.getText();
                int luong = Integer.parseInt(jtext_luong.getText());
                String query = "call addNhanVien(?,?,?,?,?)";
                pst = conn.prepareStatement(query);
                pst.setString(1, tennv);
                pst.setString(2, sdt);
                pst.setString(3, gioitinh);
                pst.setString(4, ngaysinh);
                pst.setInt(5, luong);
                rs = pst.executeQuery();
                
                
                int idnv = 0;
                try {
                    PreparedStatement pst1 = null;
                    ResultSet rs1 = null;
                    
                    String timidnv = """
                                     select idnv from nhanvien order by idnv desc
                                     """;
                    pst1 = conn.prepareStatement(timidnv);
                    rs1 = pst1.executeQuery();
                    if(rs1.next()){
                        idnv = rs1.getInt(1);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                String queryADDtaikhoan = """
                                          call addTaiKhoan(?,?,?)
                                          """;
                
                String ten[] = jtext_nhanvien.getText().split(" ");
                String taikhoan = "";
                for(String x1: ten){
                    char y[] = x1.toCharArray();
                    taikhoan = taikhoan + y[0];
                }
                taikhoan = taikhoan + String.format("%d", idtk_cur + 1);
                
                String matkhau = "12345";
                
                pst = conn.prepareStatement(queryADDtaikhoan);
                pst.setString(1, taikhoan);
                pst.setString(2, matkhau);
                pst.setInt(3, idnv);
                rs = pst.executeQuery();
                
                JOptionPane.showMessageDialog(this, "Thêm Thông tin Nhân viên thành công !");
                jtext_nhanvien.setText("");
                jtext_sdt.setText("");
                jtext_ngay.setText("");
                jtext_thang.setText("");
                jtext_nam.setText("");
                jrb_nam.setSelected(true);
                jtext_luong.setText("");
                jtext_nhanvien.requestFocus();
                idtk_cur++;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jb_thuchienActionPerformed

    private void jtext_ngayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext_ngayKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Ngày sinh phải là một số nguyên dương !");
            jtext_ngay.setText("");
            jtext_ngay.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jtext_ngay.setText("");
            jtext_ngay.requestFocus();
        }
    }//GEN-LAST:event_jtext_ngayKeyPressed

    private void jtext_thangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext_thangKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Tháng sinh phải là một số nguyên dương !");
            jtext_thang.setText("");
            jtext_thang.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jtext_thang.setText("");
            jtext_thang.requestFocus();
        }
    }//GEN-LAST:event_jtext_thangKeyPressed

    private void jtext_namKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext_namKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '.' || evt.getKeyChar() == '-') {
            JOptionPane.showMessageDialog(this, "Năm sinh phải là một số nguyên dương !");
            jtext_nam.setText("");
            jtext_nam.requestFocus();
        } else if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự !");
            jtext_nam.setText("");
            jtext_nam.requestFocus();
        }
    }//GEN-LAST:event_jtext_namKeyPressed

    private void jtext_sdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtext_sdtKeyPressed
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar())){
            JOptionPane.showMessageDialog(this, "Chỉ được nhập số hoyy !");
            jtext_sdt.setText("");
            jtext_sdt.requestFocus();
        }
    }//GEN-LAST:event_jtext_sdtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemThongTinNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb_back;
    private javax.swing.JButton jb_thuchien;
    private javax.swing.JRadioButton jrb_nam;
    private javax.swing.JRadioButton jrb_nu;
    private javax.swing.JTextField jtext_luong;
    private javax.swing.JTextField jtext_nam;
    private javax.swing.JTextField jtext_ngay;
    private javax.swing.JTextField jtext_nhanvien;
    private javax.swing.JTextField jtext_sdt;
    private javax.swing.JTextField jtext_thang;
    // End of variables declaration//GEN-END:variables
}
