/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlytiemnail;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;

/**
 *
 * @author trand
 */
public class TinhTien extends javax.swing.JFrame {

    Connection conn = connectdata.getConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    int tongtien = 0;
    String tennd, idkh;

    /**
     * Creates new form TinhTien
     */
    public TinhTien() {
        initComponents();
        jtext_tongtien.setText("0");
        setLocationRelativeTo(null);
        jlb_tenkh.setForeground(Color.decode("#C5C6C7"));
        try {
            String query = """
                           select tendv from quanlytiemnail.dichvu
                           """;
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            while (rs.next()) {
                jcb_selectDichVu.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public TinhTien(String tennguoidung, String idkhachhang) {
        initComponents();
        setLocationRelativeTo(null);
        tennd = tennguoidung;
        idkh = idkhachhang;
        jtext_tongtien.setText("0");
        jlb_tenkh.setForeground(Color.decode("#C5C6C7"));
        try {
            String query = """
                           select tendv from quanlytiemnail.dichvu
                           """;
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            while (rs.next()) {
                jcb_selectDichVu.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            String query = """
                           select tenkh from khachhang where idkh = ?
                           """;
            pst = conn.prepareStatement(query);
            pst.setInt(1, Integer.parseInt(idkhachhang));
            rs = pst.executeQuery();
            if (rs.next()) {
                jlb_tenkh.setText(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlb_tenkh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdata = new javax.swing.JTable();
        jcb_selectDichVu = new javax.swing.JComboBox<>();
        jb_thembill = new javax.swing.JButton();
        jsp_soluong = new javax.swing.JSpinner();
        jtext_tongtien = new javax.swing.JTextField();
        jb_thanhtoan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jb_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thanh Toán");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 40, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("THANH TOÁN");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(197, 198, 199));
        jLabel2.setText("Khách Hàng: ");

        jlb_tenkh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rounded-in-photoretrica (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlb_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlb_tenkh))
                .addGap(11, 11, 11))
        );

        jdata.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Dịch vụ", "Giá dịch vụ", "Số lượng", "Thành Tiền"
            }
        ));
        jdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jdata);

        jcb_selectDichVu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcb_selectDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_selectDichVuActionPerformed(evt);
            }
        });

        jb_thembill.setBackground(new java.awt.Color(40, 167, 69));
        jb_thembill.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jb_thembill.setForeground(new java.awt.Color(255, 255, 255));
        jb_thembill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-button.png"))); // NOI18N
        jb_thembill.setText("Thêm vào bill");
        jb_thembill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_thembill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_thembillActionPerformed(evt);
            }
        });

        jsp_soluong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jtext_tongtien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtext_tongtien.setFocusable(false);

        jb_thanhtoan.setBackground(new java.awt.Color(0, 123, 255));
        jb_thanhtoan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jb_thanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        jb_thanhtoan.setText("Thanh Toán");
        jb_thanhtoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_thanhtoanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Tổng tiền:");

        jb_back.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jb_back.setForeground(new java.awt.Color(0, 123, 255));
        jb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jb_back.setText("Trở về");
        jb_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtext_tongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jcb_selectDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jsp_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_thembill))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_selectDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsp_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_thembill, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtext_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jb_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_selectDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_selectDichVuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jcb_selectDichVuActionPerformed

    private void jb_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_backActionPerformed
        // TODO add your handling code here:
        if (jdata.getRowCount() != 0) {
            JOptionPane.showMessageDialog(this, "Hình như bạn quên thanh toán :>", "Thông báo thanh toán", JOptionPane.WARNING_MESSAGE);
        } else {
            new QLTN(tennd).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jb_backActionPerformed

    private void jb_thembillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_thembillActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jdata.getModel();
        int soluong = (int) jsp_soluong.getValue();
        if (soluong <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn số lượng > 0 !", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            if (jdata.getRowCount() == 0) {
                String tendv = jcb_selectDichVu.getSelectedItem().toString();
                int giadv = 1;
                try {
                    String query = """
                               select giadv from quanlytiemnail.dichvu where tendv like ?
                               """;
                    pst = conn.prepareStatement(query);
                    pst.setString(1, tendv);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        giadv = rs.getInt("giadv");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                int thanhtien = soluong * giadv;
                // in data len table
                Object rowdata[] = new Object[5];
                rowdata[0] = tendv;
                rowdata[1] = giadv;
                rowdata[2] = soluong;
                rowdata[3] = thanhtien;
                model.addRow(rowdata);
                tongtien += thanhtien;
                jtext_tongtien.setText(String.format("%d", tongtien));
                jcb_selectDichVu.setSelectedIndex(0);
                jsp_soluong.setValue(0);
            }else{
                String tendv = jcb_selectDichVu.getSelectedItem().toString();
                int giadv = 1;
                try {
                    String query = """
                               select giadv from quanlytiemnail.dichvu where tendv like ?
                               """;
                    pst = conn.prepareStatement(query);
                    pst.setString(1, tendv);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        giadv = rs.getInt("giadv");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                for(int i = 0; i<jdata.getRowCount(); i++){
                    if(tendv.equals(model.getValueAt(i, 0).toString())){
                        int thanhtien = soluong * giadv + Integer.parseInt(model.getValueAt(i, 3).toString());
                        int cur_gia = Integer.parseInt(model.getValueAt(i, 2).toString());
                        model.setValueAt(cur_gia + soluong, i, 2);
                        model.setValueAt(thanhtien, i, 3);
                        tongtien += soluong * giadv;
                        jtext_tongtien.setText(String.format("%d", tongtien));
                        jcb_selectDichVu.setSelectedIndex(0);
                        jsp_soluong.setValue(0);
                        return;
                    }
                }
                int thanhtien = soluong * giadv;
                // in data len table
                Object rowdata[] = new Object[5];
                rowdata[0] = tendv;
                rowdata[1] = giadv;
                rowdata[2] = soluong;
                rowdata[3] = thanhtien;
                model.addRow(rowdata);
                tongtien += thanhtien;
                jtext_tongtien.setText(String.format("%d", tongtien));
                jcb_selectDichVu.setSelectedIndex(0);
                jsp_soluong.setValue(0);
            }

        }
    }//GEN-LAST:event_jb_thembillActionPerformed

    private void jb_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_thanhtoanActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jdata.getModel();
        if (jdata.getRowCount() != 0) {
            int idhd = 0, iddv = 0, idnv = 0;
            LocalDate daynow = LocalDate.now();
            String new_daynow = "";
            String name_nv = "";
            String tenkh = "";
            String sdtnv = "";
            try {
                String query = """
                               select quanlytiemnail.nhanvien.idnv, quanlytiemnail.nhanvien.tennv, sdtnv from quanlytiemnail.taikhoan inner join quanlytiemnail.nhanvien
                               on quanlytiemnail.taikhoan.idnv = quanlytiemnail.nhanvien.idnv
                               where tentaikhoan like ?
                               """;
                pst = conn.prepareStatement(query);
                pst.setString(1, tennd);
                rs = pst.executeQuery();
                if (rs.next()) {
                    idnv = rs.getInt(1);
                    name_nv = rs.getString(2);
                    sdtnv = rs.getString(3);
                }
                // them hoa don
                String query1 = """
                           call addHoaDon(?, ?, ?);
                           """;
                pst = conn.prepareStatement(query1);
                pst.setInt(1, idnv);
                pst.setInt(2, Integer.parseInt(idkh));
                new_daynow = daynow.toString();
                pst.setString(3, new_daynow);
                rs = pst.executeQuery();

                PreparedStatement pst1 = null;
                ResultSet rs1 = null;
                String query2 = """
                               select idhd from quanlytiemnail.hoadon order by idhd desc
                               """;
                pst1 = conn.prepareStatement(query2);
                rs1 = pst1.executeQuery();
                if (rs1.next()) {
                    idhd = rs1.getInt(1);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            String strDichvu = "";
            String soluongdv;
            int giadv = 0;

            for (int i = 0; i < jdata.getRowCount(); i++) {
                try {
                    String query3 = """
                               select iddv, giadv from quanlytiemnail.dichvu where tendv like ?
                               """;
                    pst = conn.prepareStatement(query3);
                    pst.setString(1, model.getValueAt(i, 0).toString());
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        iddv = rs.getInt(1);
                        giadv = rs.getInt(2);
                    }
                    String query4 = """
                               call addChitiet_hd(?,?,?)
                               """;
                    pst = conn.prepareStatement(query4);
                    pst.setInt(1, idhd);
                    pst.setInt(2, iddv);
                    pst.setInt(3, Integer.parseInt(model.getValueAt(i, 2).toString()));
                    rs = pst.executeQuery();
                    soluongdv = model.getValueAt(i, 2).toString();
                    strDichvu += model.getValueAt(i, 0).toString() + " " + String.format("%d", giadv) + " "
                            + "\n Số lượng: " + soluongdv + "\n";
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            String sdtkh = "";
            try {
                String timtenkh = """
                               select tenkh, sdtkh from khachhang where idkh = ?
                               """;
                pst = conn.prepareStatement(timtenkh);
                pst.setInt(1, Integer.parseInt(idkh));
                rs = pst.executeQuery();
                if (rs.next()) {
                    tenkh = rs.getString(1);
                    sdtkh = rs.getString(2);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            // hien thi hoa don vua thanh toan
            jcb_selectDichVu.setSelectedIndex(0);
            jsp_soluong.setValue(0);
            model.setRowCount(0);
            try {
                String themlichsu = """
                               call addlichsu(?,?,?,?,?,?,?);
                               """;
                pst = conn.prepareStatement(themlichsu);
                pst.setInt(1, idhd);
                pst.setString(2, tenkh);
                pst.setString(3, sdtkh);
                pst.setString(4, name_nv);
                pst.setString(5, sdtnv);
                pst.setString(6, new_daynow);
                pst.setInt(7, Integer.parseInt(jtext_tongtien.getText()));
                pst.executeQuery();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            int choice = JOptionPane.showConfirmDialog(this, "Thanh toán thành công ! \n \t Bạn có muốn xem THÔNG TIN HÓA ĐƠN VỪA THANH TOÁN ?", "Thông báo thanh toán", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "THÔNG TIN HÓA ĐƠN  \n"
                        + "ID: " + String.format("%d", idhd) + "\n"
                        + "Tên khách hàng: " + tenkh + "\n"
                        + "Tên nhân viên: " + name_nv + "\n"
                        + "Các dịch vụ sử dụng: \n"
                        + strDichvu
                        + "Ngày lập: " + new_daynow + "\n"
                        + "Tổng tiền: " + jtext_tongtien.getText());
            } else {
                JOptionPane.showMessageDialog(this, "ID hóa đơn vừa thanh toán là: " + String.format("%d", idhd));
            }
            jtext_tongtien.setText("0");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng thêm dịch vụ trước khi thanh toán !", "Thông báo thanh toán", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jb_thanhtoanActionPerformed

    private void jdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdataMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jdata.getModel();
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa dịch vụ này không ?", "Thông báo xóa", JOptionPane.OK_CANCEL_OPTION);
        if (choice == JOptionPane.OK_OPTION) {
            String tru_tien = model.getValueAt(jdata.getSelectedRow(), 3).toString();
            int tienconlai = Integer.parseInt(jtext_tongtien.getText()) - Integer.parseInt(tru_tien);
            tongtien = tienconlai;
            jtext_tongtien.setText(String.format("%d", tienconlai));
            model.removeRow(jdata.getSelectedRow());
        }
    }//GEN-LAST:event_jdataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_back;
    private javax.swing.JButton jb_thanhtoan;
    private javax.swing.JButton jb_thembill;
    private javax.swing.JComboBox<String> jcb_selectDichVu;
    private javax.swing.JTable jdata;
    private javax.swing.JLabel jlb_tenkh;
    private javax.swing.JSpinner jsp_soluong;
    private javax.swing.JTextField jtext_tongtien;
    // End of variables declaration//GEN-END:variables
}
